
export const moviesData = [
  { id: 1, title: "Peanut Butter Falcon", average: 6.3, date: new Date("2024-03-19"), meta: {} },
  { id: 2, title: "Ronin", average: 8.314285714, date: new Date("2024-03-26"), meta: {} },
  { id: 3, title: "The Mist", average: 7.128571429, date: new Date("2024-04-02"), meta: {} },
  { id: 4, title: "Grease", average: 7.138888889, date: new Date("2024-04-09"), meta: {} },
  { id: 5, title: "Die Hard with a Vengeance", average: 7.55, date: new Date("2024-04-16"), meta: {} },
  { id: 6, title: "The Re-Animator", average: 5.708888889, date: new Date("2024-04-23"), meta: {} },
  { id: 7, title: "Sexy Beast", average: 8.275, date: new Date("2024-04-30"), meta: {} },
  { id: 8, title: "Boogie Nights", average: 8.033333333, date: new Date("2024-05-07"), meta: {} },
  { id: 9, title: "Johnny Mnemonic", average: 6.65, date: new Date("2024-05-14"), meta: {} },
  { id: 10, title: "Reign Of Fire", average: 5.5, date: new Date("2024-05-21"), meta: {} },
  { id: 11, title: "Human Traffic", average: 6.466666667, date: new Date("2024-05-28"), meta: {} },
  { id: 12, title: "Blood Simple", average: 7.383333333, date: new Date("2024-06-04"), meta: {} },
  { id: 13, title: "Everything Everywhere All At Once", average: 8.554545455, date: new Date("2024-06-11"), meta: {} },
  { id: 14, title: "Velocipastor", average: 6.185714286, date: new Date("2024-06-18"), meta: {} },
  { id: 15, title: "Antitrust", average: 6.6125, date: new Date("2024-06-25"), meta: {} },
  { id: 16, title: "Misery", average: 7.98, date: new Date("2024-07-02"), meta: {} },
  { id: 17, title: "The Abyss", average: 7.55, date: new Date("2024-07-09"), meta: {} },
  { id: 18, title: "The Thing", average: 8.925, date: new Date("2024-07-16"), meta: {} },
  { id: 19, title: "Tampopo", average: 7.014285714, date: new Date("2024-07-23"), meta: {} },
  { id: 20, title: "True Romance", average: 7.828571429, date: new Date("2024-07-30"), meta: {} },
  { id: 21, title: "The Fugitive", average: 7.566666667, date: new Date("2024-08-13"), meta: {} },
  { id: 22, title: "Rat Race", average: 7.071428571, date: new Date("2024-08-20"), meta: {} },
  { id: 23, title: "Bring it On", average: 7.222222222, date: new Date("2024-08-27"), meta: {} },
  { id: 24, title: "The Lighthouse", average: 7.854545455, date: new Date("2024-09-03"), meta: {} },
  { id: 25, title: "Blackberry", average: 7.527272727, date: new Date("2024-09-01"), meta: {} },
  { id: 26, title: "Master & Commander", average: 7.688888889, date: new Date("2024-09-17"), meta: {} },
  { id: 27, title: "Godzilla Minus One", average: 8.42, date: new Date("2024-09-24"), meta: {} },
  { id: 28, title: "Twilight", average: 4.728571429, date: new Date("2024-10-01"), meta: {} },
{ id: 29, title: "Small Soldiers", average: 6.35, date: new Date("2024-10-08"), meta: {} },
  { id: 30, title: "The Matrix", average: 8.5, date: new Date("2024-10-15"), meta: {} },
];


export const ratingsData = [
  { movieId: 1, raterName: "Walt", rating: 6.5 },
  { movieId: 1, raterName: "Jesse", rating: 6.3 },
  { movieId: 1, raterName: "Kieran", rating: 6.1 },
  { movieId: 2, raterName: "Nicole", rating: 7.5 },
  { movieId: 2, raterName: "Walt", rating: 7.4 },
  { movieId: 2, raterName: "Jesse", rating: 7.5 },
  { movieId: 2, raterName: "Kieran", rating: 10 },
  { movieId: 2, raterName: "Maggie", rating: 7.1 },
  { movieId: 2, raterName: "Jonny", rating: 8.7 },
  { movieId: 2, raterName: "Mitch", rating: 10 },
  { movieId: 3, raterName: "Nicole", rating: 8 },
  { movieId: 3, raterName: "Walt", rating: 8.5 },
  { movieId: 3, raterName: "Jesse", rating: 5.9 },
  { movieId: 3, raterName: "Kieran", rating: 6 },
  { movieId: 3, raterName: "Maggie", rating: 6 },
  { movieId: 3, raterName: "Jonny", rating: 6.4 },
  { movieId: 3, raterName: "Paddy", rating: 9.1 },
  { movieId: 4, raterName: "Nicole", rating: 9 },
  { movieId: 4, raterName: "Walt", rating: 6.3 },
  { movieId: 4, raterName: "Jesse", rating: 6.4 },
  { movieId: 4, raterName: "Kieran", rating: 7.15 },
  { movieId: 4, raterName: "Mike", rating: 10 },
  { movieId: 4, raterName: "Maggie", rating: 9 },
  { movieId: 4, raterName: "Glen", rating: 5 },
  { movieId: 4, raterName: "Jonny", rating: 5.2 },
  { movieId: 4, raterName: "Mitch", rating: 6.2 },
  { movieId: 5, raterName: "Nicole", rating: 7 },
  { movieId: 5, raterName: "Walt", rating: 7.5 },
  { movieId: 5, raterName: "Jesse", rating: 6.7 },
  { movieId: 5, raterName: "Kieran", rating: 6.8 },
  { movieId: 5, raterName: "Mike", rating: 7.8 },
  { movieId: 5, raterName: "Jay", rating: 9 },
  { movieId: 5, raterName: "Jonny", rating: 8.5 },
  { movieId: 5, raterName: "Mitch", rating: 7.1 },
  { movieId: 6, raterName: "Nicole", rating: 6.52 },
  { movieId: 6, raterName: "Walt", rating: 6.5 },
  { movieId: 6, raterName: "Jesse", rating: 5.7 },
  { movieId: 6, raterName: "Kieran", rating: 6.66 },
  { movieId: 6, raterName: "Jay", rating: 6 },
  { movieId: 6, raterName: "Maggie", rating: 4.7 },
  { movieId: 6, raterName: "Jonny", rating: 5.8 },
  { movieId: 6, raterName: "Sam", rating: 4.5 },
  { movieId: 6, raterName: "Garrett", rating: 5 },
  { movieId: 7, raterName: "Nicole", rating: 8 },
  { movieId: 7, raterName: "Walt", rating: 7.8 },
  { movieId: 7, raterName: "Jesse", rating: 8.3 },
  { movieId: 7, raterName: "Kieran", rating: 9 },
  { movieId: 8, raterName: "Nicole", rating: 8 },
  { movieId: 8, raterName: "Walt", rating: 8.3 },
  { movieId: 8, raterName: "Jesse", rating: 8.5 },
  { movieId: 8, raterName: "Kieran", rating: 8 },
  { movieId: 8, raterName: "Jonny", rating: 7.6 },
  { movieId: 8, raterName: "Mitch", rating: 7.8 },
  { movieId: 9, raterName: "Nicole", rating: 7 },
  { movieId: 9, raterName: "Walt", rating: 6.8 },
  { movieId: 9, raterName: "Jesse", rating: 6.1 },
  { movieId: 9, raterName: "Kieran", rating: 6.7 },
  { movieId: 10, raterName: "Nicole", rating: 6.7 },
  { movieId: 10, raterName: "Walt", rating: 5.8 },
  { movieId: 10, raterName: "Jesse", rating: 3.2 },
  { movieId: 10, raterName: "Kieran", rating: 5 },
  { movieId: 10, raterName: "Mike", rating: 6.8 },
  { movieId: 10, raterName: "Jay", rating: 4.2 },
  { movieId: 10, raterName: "Maggie", rating: 5.3 },
  { movieId: 10, raterName: "Glen", rating: 6.5 },
  { movieId: 10, raterName: "Mitch", rating: 6 },
  { movieId: 11, raterName: "Nicole", rating: 7.5 },
  { movieId: 11, raterName: "Walt", rating: 7.6 },
  { movieId: 11, raterName: "Jesse", rating: 6.2 },
  { movieId: 11, raterName: "Maggie", rating: 6.8 },
  { movieId: 11, raterName: "Glen", rating: 4.5 },
  { movieId: 11, raterName: "Jonny", rating: 6.2 },
  { movieId: 12, raterName: "Nicole", rating: 8.5 },
  { movieId: 12, raterName: "Walt", rating: 7.3 },
  { movieId: 12, raterName: "Jesse", rating: 7.7 },
  { movieId: 12, raterName: "Kieran", rating: 6.5 },
  { movieId: 12, raterName: "Maggie", rating: 7.1 },
  { movieId: 12, raterName: "Jonny", rating: 7.2 },
  { movieId: 13, raterName: "Nicole", rating: 9.5 },
  { movieId: 13, raterName: "Walt", rating: 8.9 },
  { movieId: 13, raterName: "Kieran", rating: 8.9 },
  { movieId: 13, raterName: "Mike", rating: 5 },
  { movieId: 13, raterName: "Jay", rating: 8.9 },
  { movieId: 13, raterName: "Maggie", rating: 9.7 },
  { movieId: 13, raterName: "Glen", rating: 8 },
  { movieId: 13, raterName: "Jonny", rating: 8.1 },
  { movieId: 13, raterName: "Mitch", rating: 9.6 },
  { movieId: 13, raterName: "Sam", rating: 9 },
  { movieId: 13, raterName: "Garrett", rating: 8.5 },
  { movieId: 14, raterName: "Nicole", rating: 8 },
  { movieId: 14, raterName: "Walt", rating: 6.9 },
  { movieId: 14, raterName: "Jesse", rating: 1.6 },
  { movieId: 14, raterName: "Kieran", rating: 6.9 },
  { movieId: 14, raterName: "Jay", rating: 6 },
  { movieId: 14, raterName: "Maggie", rating: 8.5 },
  { movieId: 14, raterName: "Jonny", rating: 5.4 },
  { movieId: 15, raterName: "Nicole", rating: 7.6 },
  { movieId: 15, raterName: "Walt", rating: 6.8 },
  { movieId: 15, raterName: "Jay", rating: 6.8 },
  { movieId: 15, raterName: "Maggie", rating: 5.8 },
  { movieId: 15, raterName: "Jonny", rating: 6.5 },
  { movieId: 15, raterName: "Mitch", rating: 6.9 },
  { movieId: 15, raterName: "Colin", rating: 7.5 },
  { movieId: 16, raterName: "Nicole", rating: 8.2 },
  { movieId: 16, raterName: "Walt", rating: 7.2 },
  { movieId: 16, raterName: "Jesse", rating: 6.7 },
  { movieId: 16, raterName: "Kieran", rating: 7.5 },
  { movieId: 16, raterName: "Mike", rating: 9.5 },
  { movieId: 16, raterName: "Jay", rating: 8.5 },
  { movieId: 16, raterName: "Maggie", rating: 7.6 },
  { movieId: 16, raterName: "Jonny", rating: 8.7 },
  { movieId: 16, raterName: "Mitch", rating: 7.9 },
  { movieId: 16, raterName: "Colin", rating: 8 },
  { movieId: 17, raterName: "Nicole", rating: 7 },
  { movieId: 17, raterName: "Walt", rating: 9.3 },
  { movieId: 17, raterName: "Jesse", rating: 6.8 },
  { movieId: 17, raterName: "Kieran", rating: 7.7 },
  { movieId: 17, raterName: "Jay", rating: 7 },
  { movieId: 17, raterName: "Jonny", rating: 7.8 },
  { movieId: 17, raterName: "Paddy", rating: 7.8 },
  { movieId: 18, raterName: "Nicole", rating: 8.5 },
  { movieId: 18, raterName: "Walt", rating: 10 },
  { movieId: 18, raterName: "Kieran", rating: 9 },
  { movieId: 18, raterName: "Mike", rating: 10 },
  { movieId: 18, raterName: "Jay", rating: 7.5 },
  { movieId: 18, raterName: "Maggie", rating: 8.7 },
  { movieId: 18, raterName: "Glen", rating: 9 },
  { movieId: 18, raterName: "Jonny", rating: 8.7 },
  { movieId: 19, raterName: "Nicole", rating: 7 },
  { movieId: 19, raterName: "Walt", rating: 5 },
  { movieId: 19, raterName: "Jesse", rating: 6.9 },
  { movieId: 19, raterName: "Mike", rating: 9.5 },
  { movieId: 19, raterName: "Maggie", rating: 5.5 },
  { movieId: 19, raterName: "Jonny", rating: 5.2 },
  { movieId: 19, raterName: "Mitch", rating: 10 },
  { movieId: 20, raterName: "Nicole", rating: 8 },
  { movieId: 20, raterName: "Walt", rating: 7.8 },
  { movieId: 20, raterName: "Jesse", rating: 7.6 },
  { movieId: 20, raterName: "Kieran", rating: 7.5 },
  { movieId: 20, raterName: "Maggie", rating: 7.1 },
  { movieId: 20, raterName: "Jonny", rating: 8.2 },
  { movieId: 20, raterName: "Mitch", rating: 8.6 },
  { movieId: 21, raterName: "Nicole", rating: 7.8 },
  { movieId: 21, raterName: "Walt", rating: 7.8 },
  { movieId: 21, raterName: "Jesse", rating: 6.8 },
  { movieId: 21, raterName: "Kieran", rating: 7.8 },
  { movieId: 21, raterName: "Maggie", rating: 7.6 },
  { movieId: 21, raterName: "Jonny", rating: 7.6 },
  { movieId: 22, raterName: "Nicole", rating: 7.2 },
  { movieId: 22, raterName: "Walt", rating: 7.5 },
  { movieId: 22, raterName: "Jesse", rating: 6.7 },
  { movieId: 22, raterName: "Kieran", rating: 7 },
  { movieId: 22, raterName: "Glen", rating: 6.5 },
  { movieId: 22, raterName: "Jonny", rating: 7.1 },
  { movieId: 22, raterName: "Mitch", rating: 7.5 },
  { movieId: 23, raterName: "Nicole", rating: 8.4 },
  { movieId: 23, raterName: "Walt", rating: 6.9 },
  { movieId: 23, raterName: "Jesse", rating: 6 },
  { movieId: 23, raterName: "Kieran", rating: 6.9 },
  { movieId: 23, raterName: "Jay", rating: 6.7 },
  { movieId: 23, raterName: "Maggie", rating: 9 },
  { movieId: 23, raterName: "Jonny", rating: 6.2 },
  { movieId: 23, raterName: "Sam", rating: 8.9 },
  { movieId: 23, raterName: "Garrett", rating: 6 },
  { movieId: 24, raterName: "Nicole", rating: 6 },
  { movieId: 24, raterName: "Walt", rating: 9 },
  { movieId: 24, raterName: "Jesse", rating: 7.4 },
  { movieId: 24, raterName: "Kieran", rating: 7.9 },
  { movieId: 24, raterName: "Mike", rating: 7.8 },
  { movieId: 24, raterName: "Maggie", rating: 9.1 },
  { movieId: 24, raterName: "Glen", rating: 9 },
  { movieId: 24, raterName: "Jonny", rating: 8.6 },
  { movieId: 24, raterName: "Mitch", rating: 8.2 },
  { movieId: 24, raterName: "Sam", rating: 6.9 },
  { movieId: 24, raterName: "Garrett", rating: 6.5 },
  { movieId: 25, raterName: "Nicole", rating: 7.4 },
  { movieId: 25, raterName: "Walt", rating: 7.6 },
  { movieId: 25, raterName: "Jesse", rating: 7.1 },
  { movieId: 25, raterName: "Kieran", rating: 7.5 },
  { movieId: 25, raterName: "Mike", rating: 7.5 },
  { movieId: 25, raterName: "Maggie", rating: 7.4 },
  { movieId: 25, raterName: "Glen", rating: 7.7 },
  { movieId: 25, raterName: "Jonny", rating: 7.5 },
  { movieId: 25, raterName: "Mitch", rating: 7.1 },
  { movieId: 25, raterName: "Sam", rating: 7.8 },
  { movieId: 25, raterName: "Garrett", rating: 8.2 },
  { movieId: 26, raterName: "Nicole", rating: 8.3 },
  { movieId: 26, raterName: "Walt", rating: 7.3 },
  { movieId: 26, raterName: "Jesse", rating: 7.5 },
  { movieId: 26, raterName: "Kieran", rating: 8 },
  { movieId: 26, raterName: "Mike", rating: 6.5 },
  { movieId: 26, raterName: "Maggie", rating: 6.9 },
  { movieId: 26, raterName: "Glen", rating: 9 },
  { movieId: 26, raterName: "Jonny", rating: 8.7 },
  { movieId: 26, raterName: "Garrett", rating: 7 },
  { movieId: 27, raterName: "Nicole", rating: 9 },
  { movieId: 27, raterName: "Jesse", rating: 7.4 },
  { movieId: 27, raterName: "Kieran", rating: 7.8 },
  { movieId: 27, raterName: "Mike", rating: 9.5 },
  { movieId: 27, raterName: "Jay", rating: 9.4 },
  { movieId: 27, raterName: "Maggie", rating: 8.8 },
  { movieId: 27, raterName: "Glen", rating: 7.5 },
  { movieId: 27, raterName: "Jonny", rating: 8.6 },
  { movieId: 27, raterName: "Sam", rating: 7.2 },
  { movieId: 27, raterName: "Garrett", rating: 9 },
  { movieId: 28, raterName: "Nicole", rating: 7.3 },
  { movieId: 28, raterName: "Walt", rating: 4.3 },
  { movieId: 28, raterName: "Jesse", rating: 2.8 },
  { movieId: 28, raterName: "Kieran", rating: 3 },
  { movieId: 28, raterName: "Mike", rating: 0.1 },
  { movieId: 28, raterName: "Jay", rating: 5 },
  { movieId: 28, raterName: "Maggie", rating: 6 },
  { movieId: 28, raterName: "Glen", rating: 2 },
  { movieId: 28, raterName: "Jonny", rating: 5.4 },
  { movieId: 28, raterName: "Mitch", rating: 5.2 },
  { movieId: 28, raterName: "Sam", rating: 6.8 },
  { movieId: 28, raterName: "Garrett", rating: 4 },
  { movieId: 28, raterName: "Kyle", rating: 6.5 },
  { movieId: 28, raterName: "Soraya", rating: 7.8 },
  { movieId: 29, raterName: "Nicole", rating: 7 },
  { movieId: 29, raterName: "Walt", rating: 6.5 },
  { movieId: 29, raterName: "Jesse", rating: 5.9 },
  { movieId: 29, raterName: "Kieran", rating: 6 },
  { movieId: 29, raterName: "Jay", rating: 6 },
  { movieId: 29, raterName: "Maggie", rating: 6.2 },
  { movieId: 29, raterName: "Glen", rating: 6 },
  { movieId: 29, raterName: "Jonny", rating: 6.4 },
  { movieId: 29, raterName: "Sam", rating: 6.5 },
  { movieId: 29, raterName: "Garrett", rating: 7 }
];